### ISSUE TITLE
APK not available

### ISSUE THREAD

**Issue by DhayanandhS** [karthickkumarsm/Guess-The-Word-App#1]
Hi, @karthickkumarsm 

I noticed that there is no APK file link available in the repository for the Guess The Word Android Application. It would be helpful to include a link to the APK file so that users can easily download and install the app for testing purposes.

Could you please add the APK file link to the repository or provide instructions on how to generate the APK from the source code?

Thank you!

**Comment by karthickkumarsm** [comment]
Thank for notifying brother :)
